// Generates public/sitemap.xml before every build (see "prebuild" in package.json).
// Static pages come from the route/slug data files; project pages are fetched from
// the backend so a new project shows up in the sitemap without any manual edit.
// If the API can't be reached, the sitemap is still written without project pages.
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SITE = "https://mgareklama.com";

const read = (file) => fs.readFileSync(path.join(ROOT, file), "utf8");

const apiRoot = () => {
  if (process.env.REACT_APP_API_ROOT) return process.env.REACT_APP_API_ROOT;
  for (const file of [".env.production", ".env"]) {
    try {
      const match = read(file).match(/^REACT_APP_API_ROOT=['"]?([^'"\r\n]+)/m);
      if (match) return match[1];
    } catch (e) {
      /* file missing */
    }
  }
  return null;
};

const serviceSlugs = () => {
  const block = read("src/data/services-content.js").match(/serviceSlugs\s*=\s*\[([\s\S]*?)\]/);
  return [...block[1].matchAll(/"([a-z0-9-]+)"/g)].map((m) => m[1]);
};

const productionSlugs = () => {
  const block = read("src/data/production-content.js").match(/IMAGE_TO_SLUG\s*=\s*\{([\s\S]*?)\}/);
  return [...block[1].matchAll(/:\s*"([a-z0-9-]+)"/g)].map((m) => m[1]);
};

const fetchProjectSlugs = async () => {
  const root = apiRoot();
  if (!root) return [];
  try {
    const response = await fetch(`${root}/projects/?lang=en`, {
      headers: { accept: "application/json" },
      signal: AbortSignal.timeout(15000),
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const data = await response.json();
    const list = Array.isArray(data) ? data : data.results || [];
    return list.map((p) => p.slug).filter(Boolean);
  } catch (error) {
    console.warn(`[sitemap] Could not load projects (${error.message}); skipping project pages.`);
    return [];
  }
};

// English has no prefix; ru/uz live under /ru and /uz (see src/serves/locale.js).
const LANGS = ["en", "ru", "uz"];
const localized = (route, lang) =>
  lang === "en" ? route : route === "/" ? `/${lang}` : `/${lang}${route}`;

// One <url> per language, each listing all language versions as alternates.
const entry = (route, changefreq, priority) => {
  const alternates = [
    ...LANGS.map(
      (l) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${SITE}${localized(route, l)}"/>`
    ),
    `    <xhtml:link rel="alternate" hreflang="x-default" href="${SITE}${localized(route, "en")}"/>`,
  ].join("\n");
  return LANGS.map(
    (lang) =>
      `  <url>\n    <loc>${SITE}${localized(route, lang)}</loc>\n${alternates}\n    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`
  ).join("\n");
};

(async () => {
  const projects = await fetchProjectSlugs();
  const entries = [
    entry("/", "weekly", "1.0"),
    entry("/about", "monthly", "0.7"),
    entry("/serves", "monthly", "0.8"),
    ...serviceSlugs().map((s) => entry(`/services/${s}`, "monthly", "0.8")),
    ...productionSlugs().map((s) => entry(`/production/${s}`, "monthly", "0.8")),
    entry("/gallery", "weekly", "0.7"),
    entry("/projects", "weekly", "0.8"),
    ...projects.map((s) => entry(`/projects/${encodeURIComponent(s)}`, "monthly", "0.6")),
    entry("/contact", "monthly", "0.7"),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.js on every build. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.join("\n")}
</urlset>
`;
  fs.writeFileSync(path.join(ROOT, "public", "sitemap.xml"), xml);
  console.log(`[sitemap] Wrote ${entries.length * LANGS.length} URLs (${entries.length} pages x ${LANGS.length} languages, ${projects.length} projects).`);
})();
